# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Site settings
title: Daniel Kolkena
tagline: ''
email: daniel.kolkena@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  The Github Pages site for Daniel Kolkena.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://dkolkena.github.io" # the base hostname & protocol for your site
paginate: 5

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/dkolkena
  - title: facebook
    url: https://facebook.com/dkolkena
  - title: github
    url: http://github.com/dkolkena

twitter_username: dkolkena
facebook_username: dkolkena
github_username:  dkolkena

# Build settings
markdown: kramdown

# Custom vars
version: 1.0.0
