# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Site settings
title: Daniel Kolkena
tagline: ''
email: daniel.kolkena@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  The Github Pages site for Daniel Kolkena.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://dkolkena.github.io" # the base hostname & protocol for your site
paginate: 5

# Contact
twitter_username: dkolkena
facebook_username: dkolkena
github_username:  dkolkena

# Build settings
markdown: kramdown

# Custom vars
version: 1.0.0
